### ISSUE TITLE
Lots of improvements to this package

### ISSUE THREAD

**Issue by NathanBaulch** [fiorix/protoc-gen-cobra#7]
Greetings, just wanted to let you know that I've made a huge number of improvements to this package during my covid-19 isolation in [this](https://github.com/NathanBaulch/protoc-gen-cobra) fork.

Some of these include:
* Migrated to the new [go protobuf V2 API](https://blog.golang.org/protobuf-apiv2) and deleted a huge amount of code
* Fixed bugs related to unused imports and `oneof` issues
* Added support for enums, maps and [well known types](https://developers.google.com/protocol-buffers/docs/reference/google.protobuf)
* Defaulted flag values from environment variables
* Made auth (dial options) and input/output formats more extensible
* Included proto comments in help usage
* Deprecated commands and flags if marked as such in proto

I can send a monolithic PR or you can cherry pick the bits you like (difficult given the magnitude of the changes) or alternatively you can just let visitors know about my fork. Whatever you prefer! Also happy to get feedback if you have the time and inclination to look over my changes.

Cheers.

**Comment by NathanBaulch** [comment]
Looping recent contributors @tetratelabs @kerinin @ZackButcher @dio @marcin-ptaszynski @gofunct in case this is of interest. Otherwise stay safe and apologies for the spam!

**Comment by joe-getcouragenow** [comment]
@NathanBaulch Cool stuff

Cant get your example to Gen and run right now...

Nature of error is:
pb/bank_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
Might be version dependency related ? . I added the version of Protoc cocktail at the bottom.

FULL BUILD LOG

````
# this gens all the CMD code for the example !!

-- Delete bins
cd /Users/apple/workspace/go/src/github.com/NathanBaulch/protoc-gen-cobra/example/pb && /Applications/Xcode.app/Contents/Developer/usr/bin/make deps-delete
rm /Users/apple/workspace/go/bin/protoc-gen-go
rm /Users/apple/workspace/go/bin/protoc-gen-go-grpc
rm /Users/apple/workspace/go/bin/protoc-gen-cobra

-- Get bins
cd /Users/apple/workspace/go/src/github.com/NathanBaulch/protoc-gen-cobra/example/pb && /Applications/Xcode.app/Contents/Developer/usr/bin/make deps
go get google.golang.org/protobuf/cmd/protoc-gen-go
go: found google.golang.org/protobuf/cmd/protoc-gen-go in google.golang.org/protobuf v1.25.0
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc
go get github.com/NathanBaulch/protoc-gen-cobra

-- Delete generated files
cd /Users/apple/workspace/go/src/github.com/NathanBaulch/protoc-gen-cobra/example/pb && /Applications/Xcode.app/Contents/Developer/usr/bin/make clean
rm -f bank.pb.go cache.pb.go crud.pb.go cyclical.pb.go deprecated.pb.go nested.pb.go proto2.pb.go timer.pb.go types.pb.go bank_grpc.pb.go cache_grpc.pb.go crud_grpc.pb.go cyclical_grpc.pb.go deprecated_grpc.pb.go nested_grpc.pb.go proto2_grpc.pb.go timer_grpc.pb.go types_grpc.pb.go bank.cobra.pb.go cache.cobra.pb.go crud.cobra.pb.go cyclical.cobra.pb.go deprecated.cobra.pb.go nested.cobra.pb.go proto2.cobra.pb.go timer.cobra.pb.go types.cobra.pb.go

-- DO the gen generated files
cd /Users/apple/workspace/go/src/github.com/NathanBaulch/protoc-gen-cobra/example/pb && /Applications/Xcode.app/Contents/Developer/usr/bin/make 
protoc \
                -I. \
                --go_out=. \
                --go-grpc_out=. \
                --cobra_out=. \
                bank.proto cache.proto crud.proto cyclical.proto deprecated.proto nested.proto proto2.proto timer.proto types.proto


-- Run the CLI example build...
cd /Users/apple/workspace/go/src/github.com/NathanBaulch/protoc-gen-cobra/example && go build -o /Users/apple/workspace/go/src/github.com/joe-getcouragenow/junk/archi/grpc/gen/cmd/NathanBaulch__protoc-gen-cobra/bin/ex-cli .
# github.com/NathanBaulch/protoc-gen-cobra/example/pb
pb/bank_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
pb/bank_grpc.pb.go:71:28: undefined: grpc.ServiceRegistrar
pb/cache_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
pb/cache_grpc.pb.go:233:29: undefined: grpc.ServiceRegistrar
pb/crud_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
pb/crud_grpc.pb.go:167:28: undefined: grpc.ServiceRegistrar
pb/cyclical_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
pb/cyclical_grpc.pb.go:71:32: undefined: grpc.ServiceRegistrar
pb/deprecated_grpc.pb.go:14:11: undefined: grpc.SupportPackageIsVersion7
pb/deprecated_grpc.pb.go:81:34: undefined: grpc.ServiceRegistrar
pb/deprecated_grpc.pb.go:81:34: too many errors
make: *** [ex-cli-build] Error 2
````


ENV 
````
-- envoy --
/usr/local/bin/envoy

envoy  version: 50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/clean-getenvoy-2aa564b-envoy/RELEASE/BoringSSL


-- grpcli --
/usr/local/bin/grpc_cli


-- grpcui --
/Users/apple/workspace/go/bin/grpcui
grpcui dev build <no version set>


-- protoc --
/usr/local/bin/protoc
protoc --version
libprotoc 3.13.0


-- protoc-gen-go --
/Users/apple/workspace/go/bin/protoc-gen-go
protoc-gen-go v1.25.0


-- protoc-gen-grpc-gateway --
/Users/apple/workspace/go/bin/protoc-gen-grpc-gateway

-- protoc-gen-swagger --
/Users/apple/workspace/go/bin/protoc-gen-swagger

-- protoc-gen-go-grpc --
/Users/apple/workspace/go/bin/protoc-gen-go-grpc
````

**Comment by NathanBaulch** [comment]
I ran into the same issue recently and was able to work around it by fetching a specific version of the yet-to-be-released `protoc-gen-go-grpc` tool.

You can grab that version with:
```shell
go get google.golang.org/grpc/cmd/protoc-gen-go-grpc@v0.0.0-20200825170228-39ef2aaf62df
```

**Comment by fiorix** [comment]
Hey this looks amazing, thanks for sharing it here.

I don't have plans to actively maintain this repo but if you could send a PR at least we could keep things in sync.

**Comment by damianoneill** [comment]
@NathanBaulch looking at your repo, there is no issues list available, so leaving a comment here.  Is it possible to define what license this code is released under?  MIT, Apache, etc.

**Comment by NathanBaulch** [comment]
Good question. I just assumed my derivative work would be covered by the forked `LICENSE` file, though I admit I never actually opened it up to take a look. Looking at it now, I'm wondering if it was just copied from the `protoc-gen-go` project license file that this project was originally based on. Hardly seems relevant anymore now that my fork has changed pretty much every line of code with the migration to the Go Protobuf V2 API, but IANAL so I'm not sure if I'm entitled to just pick another license. 🤷

**Comment by ZackButcher** [comment]
IANAL, but as I understand it you _should_ be fine releasing the BSD3 derivative code under (certain) non-BSD-3-clause licenses, e.g. Apache v2. You probably need to keep the current license in a NOTICES file (which is attempting to satisfy Clause 1 of the license). To be totally kosher you probably need to get consent from the other contributors too (but again, IANAL). I can speak for the Tetrands in saying that we give consent to relicense any code we contributed to a permissive license, eg Apache v2.

But probably more importantly, assuming @fiorix is gives a nod, I doubt Google would care in this case either. I can reach out to some open source programs office folks at Google if you're concerned, but overall I would be surprised if there were any issues on their part (FWIW while I was there we moved gRPC from BSD3 to Apache v2, but Google had a CLA in place there to cover any consent concerns).

**Comment by fiorix** [comment]
I am totally fine with re-licensing. The license in this repo was simply copied from the protobuf one when I wrote the initial code, and never looked back.

**Comment by stkrzysiak** [comment]
@NathanBaulch Great efforts over Covid, thank you!  Can you create a PR to update this repo?  
@fiorix If you do not intend to actively maintain this repo what is the process to hand it off to others? (also, thanks for putting this together initially).

**Comment by NathanBaulch** [comment]
The migration to the protobuf V2 API basically involved rewriting the whole package. I don't believe there's any interest in maintaining this original repo so I was just going to let people organically discover my fork. I guess I could move my maintenance work over here if someone makes me a contributor.

**Comment by fiorix** [comment]
If you would like to send a PR to change the README of this repo, indicating that the project has migrated to your repo, I'm willing to merge it in and freeze the repo. I have no intention to continue development any further.

Thanks!

**Comment by fiorix** [comment]
Calling it done. Thanks everyone who contributed to this and especially to @NathanBaulch for keeping it going.
